# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_projects/final_test3/final_test.srcs/sources_1/ip/green/green.xci
# IP: The module: 'green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_projects/final_test3/final_test.gen/sources_1/ip/green/green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'green'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/vivado_projects/final_test3/final_test.srcs/sources_1/ip/green/green.xci
# IP: The module: 'green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_projects/final_test3/final_test.gen/sources_1/ip/green/green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'green'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
