# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/github/zju/LogicAndComputerFundermental/final_project/final_tetris/final_test4/final_test.srcs/sources_1/ip/blue/blue.xci
# IP: The module: 'blue' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/github/zju/LogicAndComputerFundermental/final_project/final_tetris/final_test4/final_test.gen/sources_1/ip/blue/blue_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blue'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/github/zju/LogicAndComputerFundermental/final_project/final_tetris/final_test4/final_test.srcs/sources_1/ip/blue/blue.xci
# IP: The module: 'blue' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/github/zju/LogicAndComputerFundermental/final_project/final_tetris/final_test4/final_test.gen/sources_1/ip/blue/blue_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blue'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
